name: Spring Boot CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Setup MySQL Docker container
        uses: docker/compose@v2
        with:
          build: ./docker-compose.yml

      - name: Google Java Format
        uses: google-java-format/google-java-format-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: mvn clean test

      - name: Generate code coverage report
        run: |
          mvn org.jacoco:jacoco-maven-plugin:0.8.7:report
          mvn sonar:sonar \
            -Dsonar.projectKey=cf-test \
            -Dsonar.organization=felicitasyeboah \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Analyze code coverage
        run: |
          cat target/site/jacoco/index.html | grep -q "Y4:0"
          if [ $? -eq 0 ]; then
            echo "Code coverage threshold met!"
          else
            echo "Code coverage threshold NOT met!"
            exit 1
          fi

